project:
  type: website
  output-dir: docs

website:
  title: "Methods"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Photogrammetry.qmd
      - Morph.qmd
      - R_Analysis.qmd

format:
  html:
    theme: Sandstone
    css: styles.css
    toc: true
    




