project:
  type: website
  output-dir: docs

website:
  title: "Methods"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - Research.qmd
      - Photogrammetry.qmd
      - Morph.qmd
      - data_processing.qmd 
      - R_Analysis.qmd
      

format:
  html:
    theme: Sandstone
    css: styles.css
    toc: true
    
    




