---
title: "Research Background and Aims"
---

## Abstract

The classification of fossil populations informs on such evolutionary dynamics as reproductive and behavioral cohesion, adaptation, and patterns of divergence, anagenesis, and reticulation. Species designations therefore provide the individual components from which we articulate our understanding of human evolutionary pattern and process. Determining how these populations should be classified, however, is a daunting task often spurring debate and conflicting interpretation. Here I build on efforts to disentangle variation from diversity in the human fossil record. Such research is of relevance in Late Chibanian paleoanthropology as new designations are being offered and debated for fossils across Africa and Eurasia (e.g., Homo longi, Homo juluensis, and Homo bodoensis). 

Barring the existence of observable autapomorphies, the determination of intraspecific versus interspecific relationships between penecontemporaneous hominin fossils is a troubling task. Researchers pursuing this objective are left with the duty of quantifying variation metrically to determine if an assemblage fits within or exceeds an acceptable range for a single species (B. A. Wood et al., 1991; B. Wood & Lonergan, 2008). Strategies employed to make such determinations commonly make use of modern analogs as models of how much variation can be observed within a taxon (Albrecht & Miller, 1993; Jolly, 1993; Mayr, 1950; Rose & Bown, 1993). For the human fossil record such comparative models often involve samples of modern Homo sapiens as well as populations of African non-human primates such as Pan, Gorilla, Papio, and Macaca (Baab, 2008; Harvati et al., 2004; B. A. Wood et al., 1991; B. Wood & Lonergan, 2008). While the applicability of these models has been debated on different grounds (phylogenetic relationships, ecology, behavior, and dimorphism to name a few), a likely greater concern with use of such samples is their narrow temporal scope (Baab, 2008; Mayr, 1950). Specimens included in contentious fossil assemblages are commonly separated in time by tens to hundreds of thousands of years. The fossils referenced in debates regarding the existence and relationships of *Homo heidelbergensis*, for example, are situated in time from as recent as 125 ka (Broken Hill 1) to 450 ka (Arago 21/47) or even 600 ka (Bodo). It is unlikely that the use of modern assemblages can satisfactorily illustrate species wide variation on this temporal scale. If the variance exhibited by a hominin fossil assemblage is to be tested against a model species, the model therefore needs to account for the degree of evolutionary change which occurs over extensive periods of time and through episodes of local selection, gene flow, drift, and etcetera. 

This project aims to generate a more comprehensive comparative model for research into hominin variation and fossil species in paleoanthropology and to use this model to test contentious taxonomic issues in Middle Pleistocene paleoanthropology. The primary agenda pursued here will be to gather a temporally deep and geographically diverse H. sapiens sample from which variation can be quantified. In first part of the project, cranial landmark data will be collected and analyzed through a 3D Geometric Morphometrics framework to investigate 1) the extent of variation identifiable in our species, 2) shifts in variation through time, and 3) evolutionary trends in cranial form. The results of this endeavor will then be tested against the variable *Homo heidelbergensis* senso stricto and senso lato assemblages. Following Roksandic et al. (2022a), this second part of the project will investigate the appropriateness of redistributing the *H.heidelbergensis* senso stricto and senso lato assemblages into a larger H. neanderthalensis classification and/or a newly offered *Homo bodoensis* species. 


### Research Objectives

1)	Investigate the range of cranial variation of *Homo sapiens* through time and space 
	a.	Develop a variance metric (CV) for a model taxon to be used against fossil assemblages when investigating taxonomic rank
	
	b.	Identify disparity in variance (D2) in different temporal segments of *H. sapiens* evolution (Late Chibanian, Late Pleistocene, Mesolithic, Neolithic, Modern)
	
	c.	Determine if we have reduced variation in response to societal factors (e.g., innovation of agriculture, transition to sedentism, increased cross-regional gene flow)
	
	d.	Determine if modern *H. sapiens* qualify as a good model for comparisons of variance within the human fossil record or if the temporally deep assemblage is preferred
	
2)	Use the Coefficient of Variation from the inclusive *Homo sapiens* sample to investigate species boundaries within the genus Homo

	a.	Test four alternate groupings of Chibanian and Late Pleistocene (CLP) hominins: *H. heidelbergensis s.l., H. heidelbergensis s.s., H.neanderthalensis w/H. heidelbergensis s.s.*, and *H. bodoensis*
	
	b.	Illustrate whether *H. heidelbergensis* is better situated with *H. neanderthalensis* and *H. bodoensis* and/or (depending on senso stricto and senso lato assessments) is better regarded as a standalone species
	
### Sampling methods

Sampling will be limited to crania from members of the genus Homo. Thus far, the sample includes a collection of 192 recent Homo sapiens spanning North America, Europe, and Africa. The age range for this collection spans over 2500 years (550 BCE to modern day).  One Middle Paleolithic specimen, the Singa cranium (150-120 ka), is also a part of the H. sapiens sample. In addition to the H. sapiens collection, the current sample includes five Middle and Lower Paleolithic crania variably attributed to Homo heidelbergensis, Homo erectus, and Homo longi (Table 1). All materials are (will be) digitized through photogrammetry unless provided from an outside source (e.g., Certosa Cemetary and Semna South). In the latter sample sets, specimens are digitized via CT scanning. Photogrammetry, the sole method for digitizing new materials in this study, is non-invasive and requires minimal handling of the materials being observed. Images are captured on a Foldio smart turntable using the Foldio 360 phone app and a Canon EOS 5D DSLR camera. These then are processed through Adobe Lightroom and Reality Capture to develop 3D digital models. 

Cranial variation is to be determined through geometric morphometric methods capturing shape profiles using craniofacial landmarks and semilandmarks. Landmark placement and data collection will be accomplished digitally through the Slicer IGT and SlicerMorph extensions in the free 3D Slicer software. A set of 32 landmarks is being employed to collect data on complete cranial samples of H. sapiens (Table 2). With many of the landmarks being bilateral, the total number of coordinates amounts to 55. This complete set of landmarks (visualized in Fig. 1) is currently being applied to all recent H. sapiens samples (JABSOM, Certosa Cemetery, and Semna South). Where skeletal damage is identified, bilateral landmarks are captured through mirroring of crania along the midsagittal plane (obtained through the application of unpaired landmarks) (Green et al., 2017; Gunz et al., 2009; Lautenschlager, 2016). Materials, particularly from fossil samples, missing larger regions for landmarking will influence the development of adjusted landmark sets (see below). The extensive list of landmarks was chosen to both capture as much variation as possible and to assess where the sample varies the most. Knowing that much of the older sample will lack the necessary features for a large portion of the proposed landmark set, I intend to illustrate how much variation goes unmeasured in such analyses. With the inclusion of more materials, particularly when incorporating fossil specimens, landmarks will largely be chosen based on the preservation of fossils. At a minimum, the latter study will follow Baab (2008) in using a truncated 16 landmark set designed to capture the basic shape of the cranial vault. 
